### ISSUE TITLE
Build libargparse from source, remove pre-built static library

### ISSUE THREAD

**Issue by barracuda156** [c0d-0x/cruxpass#4]
@c0d-0x Hi, this is on macOS, but gonna fail on any other OS likewise, because the source uses pre-built static lib:
```
/opt/local/var/macports/build/cruxpass-f0992f8e/work/compwrap/cc/usr/bin/gcc-4.2 -Os -std=c99 -I/opt/local/libexec/sqlcipher/include -arch ppc build/cruxpass.o build/database.o build/enc.o build/main.o build/tui/chalk.o build/tui/display.o build/tui/helpers.o build/tui/input.o build/tui/pipeline.o build/tui/queue.o build/tui/tui.o -o bin/cruxpass -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc ./lib/*.a -lsodium  -lncurses -lpanel -lm /opt/local/libexec/sqlcipher/lib/libsqlite3.dylib -ldl -lpthread
ld: warning: ignoring file ./lib/libargparse.a, file was built for archive which is not the architecture being linked (ppc): ./lib/libargparse.a
Undefined symbols for architecture ppc:
  "_argparse_describe", referenced from:
      _parse_options in main.o
  "_argparse_help_cb", referenced from:
      _C.22.9172 in main.o
  "_argparse_init", referenced from:
      _parse_options in main.o
  "_argparse_parse", referenced from:
      _parse_options in main.o
  "_argparse_usage", referenced from:
      _parse_options in main.o
ld: symbol(s) not found for architecture ppc
collect2: ld returned 1 exit status
make: *** [bin/cruxpass] Error 1
```

**Comment by barracuda156** [comment]
Is it this one? https://github.com/maryla-uc/libargparse 
If yes, we got a [port](https://ports.macports.org/port/libargparse) for it.

**Comment by c0d-0x** [comment]
Hi @barracuda156, good to see cruxpass on mac. Since I'm more active on linux, i've tested the project on major distros but not mac or windows. The problem is with the archive. I'm work a lightweight arg parser but for now, I'll just drop the argparser source in the project's src. That should fix the problem since argparser is relatively small anyways.

**Comment by c0d-0x** [comment]
> Is it this one? https://github.com/maryla-uc/libargparse If yes, we got a [port](https://ports.macports.org/port/libargparse) for it.

No, it this arge parser https://github.com/cofyc/argparse but the above seem interesting.

**Comment by c0d-0x** [comment]
Let me know if this worked for. https://github.com/c0d-0x/cruxpass/issues/4#issuecomment-3321625126

**Comment by c0d-0x** [comment]
I've fix the issue on my recent push. It took me a while refactoring but   cruxpass now reads stores it's databases `~/.local/share/cruxpass/`  by default and does not rely on the make file.   I've also  added is a new option to specify where you want cruxpass to read and store databases. Check it out and I'll love your feed back. commit here:  075c434251f7f2a680110567ea966f9063582440

**Comment by c0d-0x** [comment]
@barracuda156 Can you confirm on this issue so I can close it up. I've properly test cruxpass with the new features and I believe it's stable enough. Let me know if you where able port it for Port System and that the initial issue discuss here  https://github.com/c0d-0x/cruxpass/issues/4#issuecomment-3329625293  has been solved.
Thank you.

**Comment by c0d-0x** [comment]
Hi @barracuda156 ,
I looked into `mlterm` on Linux, but I wasn’t able to reproduce the same misbehavior you experienced with cruxpass. Below are some screenshots for reference. The issues you’re seeing with cruxpass might be OS-dependent, since I couldn’t reproduce them on mlterm or other terminals on Linux either. The screenshots below are from `ubuntu` [`mlterm` with defaults settings].

<img width="871" height="585" alt="Image" src="https://github.com/user-attachments/assets/c312519a-b15e-4d05-bfb1-739ffb06c897" />

<img width="1020" height="573" alt="Image" src="https://github.com/user-attachments/assets/6adee75f-9ac3-4522-8c95-93fb4f31d38e" />

**Comment by barracuda156** [comment]
Thank you. I will try from the current master in a few terminals then, and on other macOS versions (I have 4, plus 2 in VM). Will update you soon.

**Comment by barracuda156** [comment]
@c0d-0x This is still on 10.6, and I can confirm that the app works generally, but the issue with initial password prompt line (upon `cruxpass -n`) appearing above earlier terminal output remains.

<img width="805" height="509" alt="Image" src="https://github.com/user-attachments/assets/f149d9b9-1240-43e4-874d-362d61efed55" />

<img width="802" height="505" alt="Image" src="https://github.com/user-attachments/assets/72b3f5f9-e3c5-4284-81bd-466b6ad1c26c" />

<img width="804" height="504" alt="Image" src="https://github.com/user-attachments/assets/8ea15d5a-200e-4a68-acfe-ad3b4b87b811" />

**Comment by c0d-0x** [comment]
Awesome, from the screenshots I also noticed the the TUI isn't working properly because normally, the term is cleared before drawing or  any operation. 

<img width="492" height="84" alt="Image" src="https://github.com/user-attachments/assets/8257d65c-ac7d-446f-88b6-e95d115bddd4" />

This reminds me of a bug I fixed a few commits ago [ `Record 1 of 0` ].  I hope you’re using the latest version from `main`.

I want to mention that I've never been on mac-OS, so I can't say much about `termbox2`'s compatibility with Mac terminals (the TUI and all input functionalities are implemented with termbox2). I’d love to see cruxpass run smoothly on mac-OS, though.

I also noticed this  issue is inherently long and nested, you can create a new issue for mac-OS compatibility as you’re more familiar with the misbehavior from the mac-OS side.

Right now, I have little to no idea what’s causing the issue, and it might take me some time to figure it out and fix it.
    
Again, thanks  for you contributions and opening this issue.

**Comment by barracuda156** [comment]
Are there some other C-based projects using termbox2? May be helpful to compare the output and see if they exhibit the same issue.

**Comment by barracuda156** [comment]
@c0d-0x I build from 6177fc046d33c1da61f1e46f3c06299d8412bd94 now. Tried on Catalina x86_64, there is no bug with initial prompt, but `Record 1 of 0` is still present:

<img width="511" height="371" alt="Image" src="https://github.com/user-attachments/assets/bc5f6881-f512-492d-b742-79b0bce11b65" />
<img width="510" height="371" alt="Image" src="https://github.com/user-attachments/assets/7dccfc2c-0250-45ab-90b4-e4ece82974ea" />
<img width="637" height="544" alt="Image" src="https://github.com/user-attachments/assets/56908e26-6a25-405c-89fb-3b668ac55182" />

**Comment by barracuda156** [comment]
@c0d-0x I opened a new issue and close this one, since `libargparse` question is resolved.
